#!/bin/bash

SCRIPTSDIR=$(dirname $(realpath $0))

TIME=$(date +%s)
DATE=$(date +%Y%m%d)

latest=
snapshots=

for file in $(
wget http://dev.gentoo.org/~grobian/distfiles/ -O- -o /dev/null |
grep -E 'prefix-overlay-[0-9]*.tar.bz2' |
sed -e 's/^.*<a href="\(prefix-overlay-[0-9]*.tar.bz2\)">.*$/\1/'
); do
	base=${file%.tar.bz2}
	date=${base#prefix-overlay-}
	timestamp=$(date +%s --date=${date})
	
	if [[ $timestamp -ge $(($TIME - 21 * 86400)) ]]; then
		# Whitelist all snapshots less than three weeks old...
		snapshots="$snapshots $date"
	elif [[ -z $latest ]] || [[ $(date +%s --date=$latest) -lt $timestamp ]]; then
		# Plus the latest snapshot more than three weeks old.
		# This guarantees that someone with a three-weeks-old bootstrap script
		# can still bootstrap with that script.
		latest=$date
	fi
done
snapshots="$snapshots $latest"
latesttime=$(date +%s --date=${latest})

for snapshot in $snapshots; do
	if ! [[ -e distfiles-prefix-snapshot-system-$snapshot ]]; then
		dir=prefix-snapshot-$snapshot
		rm -rf $dir
		mkdir $dir
		cd $dir
		wget http://dev.gentoo.org/~grobian/distfiles/prefix-overlay-$snapshot.tar.bz2 -o /dev/null
		tar xf prefix-overlay-$snapshot.tar.bz2
		rm prefix-overlay-$snapshot.tar.bz2
		
		rm -f system-packages
		touch system-packages
		for profile in $(find portage/profiles/prefix -type d); do
			[[ -e $profile/make.defaults ]] || continue
			[[ $(find $profile -type d | wc -l) = 1 ]] || continue
			
			rm -rf etc/portage
			mkdir -p etc/portage
			ln -s ../../$profile etc/portage/make.profile
			python "${SCRIPTSDIR}"/list-system-target.py portage . >> system-packages 2>/dev/null
		done
		
		python "${SCRIPTSDIR}"/find-system-distfiles.py portage $(sort system-packages | uniq) > ../distfiles-prefix-snapshot-system-$snapshot
		
		cd ..
		rm -rf $dir
	fi
done

for file in distfiles-prefix-snapshot-system-*; do
	filedate=${file#distfiles-prefix-snapshot-system-}
	timestamp=$(date +%s --date=$filedate)
	if [[ $timestamp -lt $latesttime ]]; then
		rm -rf "${file}"
	fi
done

echo "\
# Ruud Koolen <redlizard@gentoo.org> ($(date '+%d %b %Y'))
# Files used during prefix bootstrap (all @system packages)
# that are present in the bootstrap snapshot, or were present up to three weeks ago
# NOTE: This file is autogenerated, changes will be overwritten.
# Contact redlizard@gentoo.org for details.
" > prefix-bootstrap-snapshot-whitelist

cat distfiles-prefix-snapshot-system-* | sort | uniq >> prefix-bootstrap-snapshot-whitelist
